import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./_components/Header";
import { ThirdwebProvider } from "thirdweb/react";

const commonFont = localFont({
  src: "../../public/fonts/upheaval-tt-brk/upheavtt.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Buffast",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThirdwebProvider>
        <body className={`${commonFont.className} relative antialiased`}>
          <Header />
          <main>{children}</main>
        </body>
      </ThirdwebProvider>
    </html>
  );
}
