import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const commonFont = localFont({
  src: "../../public/fonts/upheaval-tt-brk/upheavtt.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Buffast",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${commonFont.className} antialiased`}>{children}</body>
    </html>
  );
}
